# SPDX-FileCopyrightText: 2021 David Hurka <doxydoxy@mailbox.org>
#
# SPDX-License-Identifier: CC0-1.0 OR MIT

morelights_dim_ci_nodejs:
    image: debian:testing
    only:
        refs:
            - merge_requests
        changes:
            - '**/*.md'
    before_script:
        - apt-get update
        - apt-get install --yes --no-install-recommends eatmydata
        - eatmydata apt-get install --yes --no-install-recommends npm git
        - npm install -g markdownlint-cli
    script:
        - markdownlint --fix `find . \( -name '*.md' \)` || git diff --exit-code

morelights_dim_ci_reuse:
    image:
        name: fsfe/reuse:latest
        entrypoint: [""]
    only:
        - merge_requests
    script:
        - reuse lint

morelights_dim_ci_lua:
    image: debian:testing
    only:
        - merge_requests
    before_script:
        - apt-get update
        - apt-get install --yes --no-install-recommends eatmydata
        - eatmydata apt-get install --yes --no-install-recommends build-essential luarocks
        - luarocks install busted
        - luarocks install luacheck
    script:
        - busted .
        - luacheck .

morelights_dim_ci_luaformat:
    image: debian:testing
    only:
        refs:
            - merge_requests
        changes:
            - '**/*.lua'
    before_script:
        - apt-get update
        - apt-get install --yes --no-install-recommends eatmydata
        - eatmydata apt-get install --yes --no-install-recommends git ca-certificates build-essential cmake ninja-build
        - (cd /tmp && git clone --recurse-submodules https://github.com/Koihik/LuaFormatter.git)
        - (cd /tmp/LuaFormatter && mkdir build && cd build && cmake -G Ninja ..)
        - (cd /tmp/LuaFormatter/build && ninja install)
    script:
        - lua-format `find . \( -name '*.lua' \)` --check --in-place || (git diff && (false))
